

>P1;ecm29_684_1749
sequence:ecm29_684_1749:  : :  : ::::
KLATKFVDKTEWIKSLMNNSKEEMRELAALFYSV-VVSTVS-GNELKSMIEQLIKTTKDNHSPEIQHGSLLALGFTVGRY-LAKKKMRMSEQQDLERN
ADTLPDQEELIQSATETIGSFLDS-TSPLLAIAACTALGEIGRNGPLPIPSEGSGFTKLHLVESLLSRIPSSKETNKMKERAIQTLGYFPVGDGDFPHQK
LLLQGLMDSVEAKQIELQFTIGEAITSAAIGTSSVAARDAWQMTEEEYTPPAGAKVNDVVPWVLDVILNKHIISPNPHVRQAACIWLLSLVRKLSTHKEV
KSHLKEIQSAFVSVLSEN--DELSQDVASKGLGLVYELGNE------QDQQELVSTLVETLMTGKRVKHEVSGETVVFQGGALGKTPDGQ----------
---------GLSTYKELCSLASDLSQPDLVYKFMNLAN---HHAMWNSRKGAAFGFNVIATRAGEQLAPFLPQLVPRLYRYQFDPNLGIRQAMTSIWNAL
VTDKS--MVDKYLKEILQDLVKNLTSNM-WRVRESSCLALNDLLRGRPLDDIIDKLPEIWETLFRVQDDIKESVRKAAELALKTLSKVCVKMCDPAKGAA
GQRTIAALLPCLLDKGMMS--TVTEVRALSINTLVKISKSAG-AMLKPHAPKLIPALLESLSVLEPQVLNYLSLRATEQEKAAMDSARLSAAKSSPMMET
INMCLQYLDVSVLGELVPRLCELIRSGVGLGT----------------------------------KGGCASVIVSLTTQCPQDLTPYSGKL-MSALLSG
LT-DRNSVIQKSCAFAMGHLVRTSRD----------SSTEKLLQKLNGWY-MEKEEPIYKTSCALTIHAIGRYSPDVL-KNHAKEVLPLAFLGMH-----
--------------EIADEEKSEKEECNLWTEVWQENVPGSFGGIRLYLQELITITQKALQSQSWKMKAQGAIAMASIAKQTSSLVPPYLGMILTALLQG
LAGRTWAGKEELLKAIACVVTACSAELEKSVPNQPSTNEILQAVLKECSKEN------VKYKIVAISCAADILKATKEDRFQEFSNIVIPLIKKNSLESS
GVRTTKNEEENEKEKELQLEYLLGAFESLGKAWPRNAETQ--RCYRQELCKLMCERL--KLSTWKVQLGVLQ*

>P1;3w3w
structure:3w3w:  3: A: 1055 :A ::::
ALPEEVNRTLLQIVQAFAS-DNQIRSVAEKALSEEWITENNIEYLL----TFLAEQAAFSQDTTVAALSAVLFRKLALKAPITHIRK-----------
--------EVLAQIRSSLLKGFLSERADSIRHKLSDAIAECVQDDLP-----A----WPELLQALIESLKS--GNPNFRESSFRILTTVPYLIT-AVDIN
SILPIFQSGFTDASDNVKIAAVTAFVGYFKQLPKSEW----------------SKLGILLPSLLNSL-PRFLDDGKDDALASVFESLIELVELAP--KLF
KDMFDQIIQFTDMVIKNKDLEPPARTTALELLTVFSENAPQMCKSNQNYGQTLVMVTLIMMTEVS----------------------IDDDDAAEWIESD
DTDDEEEVTYDHARQALDRVALKLGGEYLAAPLFQYLQQMITSTEWRERFAAMMALSSAAEGCADVLIGEIPKILDMVIPLINDPHPRVQYGCCNVLGQI
STDFSPFIQRTAHDRILPALISKLTSECTSRVQTHAAAALVNFSEFASKDILEPYLDSLLTNLLVLLQSNKLYVQEQALTTIAFIAEAAKNKF-------
-IKYYDTLMPLLLNVLKVN----SVLKGKCMECATLIGFAVGKEKFHEHSQELISILVALQNSD---------------------ALRSYLEQ---SWSR
ICRILGDDFVPLLPIVIPPLLITAKATQDVGLIEEEEAANFQQYPDWDVVQVQGKHIAIHTSVLDDKVSAMELLQSYATLLRGQFAVYVKEVMEEIALPS
LDFYLHDGVRAAGATLIPILLSCLLAA-----EELVLLWHKASSKLIGGLMSEPMPEITQVYHNSLVNGIKVMGDNCLSEDQLAAFTKGVSANLTDTYER
MQDR----DEYNE------DFTDEDLLDEINKSIAAVLKTTNGHYLKNLENIWPMINTFLL--EPILVIFALVVIGDLIQY--EQTASMKNAFIPKVTEC
LISPDARIRQAASYIIGVCAQYAPSTYA------DVCIPTLDTLVQIVD--GSKLEENRSSTENASAAIAKILYAYNSNIP---DTYTANWFKTLPTI--
----TDK------------EAASFNYQFLSQ--------VCAQSNISAVVDSVIQALNERSLT------VIS*


>P1;ecm29_352_504
sequence:ecm29_352_504:  : :  : ::::
PANIQVVYDGLFGTNTNSKLRTLSLQFVHHICITCPEIKIKPLGPMLLNGLTKLINEYKEDPKLLSMAYSAVGKLSSRMPHLFTKDIALVQQLFEALCKE
EPETRLAIQEALSMMVGAYSTLEG------AQRTLMEALVASYLIK-PEVQVRQVAVKFA*

>P1;1u6g
structure:1u6g:  5: C: 158 :C ::::
SYHISNLLEKMT--SSDKDFRFMATNDLMTELQKDSIKLDDDSERKVVKMILKLLED--KNGEVQNLAVKCLGPLVSKVKE--YQVETIVDTLCTNMLSD
KEQLRDISSIGLKTVIGELP-----SALAANVCKKITGRLTSAIAKQEDVSVQLEALDIM*


